version: '3.4'

services:
  stream-engine:
    build: .
    environment:
      # Streamhub config
      STREAM_NAME: test-stream
      SOURCE_SYSTEM: cz.icecars.iot-iot4cps-wp5.CarFleet
      TARGET_SYSTEM: at.datahouse.iot-iot4cps-wp5.RoadAnalytics
      KAFKA_BOOTSTRAP_SERVERS: ${HOST_IP}:9092
      FILTER_LOGIC: "{}"
