version: '3.4'

services:
  stream-engine:
    build: .
    environment:
      # Streamhub config
      STREAM_NAME: test-stream
      SOURCE_SYSTEM: is.iceland.iot4cps-wp5-WeatherService.Stations
      TARGET_SYSTEM: cz.icecars.iot4cps-wp5-CarFleet.Car1
      KAFKA_BOOTSTRAP_SERVERS: ${HOST_IP}:9092
      FILTER_LOGIC: "SELECT 'Station_1.Air Temperature' FROM is.iceland.iot4cps-wp5-WeatherService.Stations
       WHERE 'Station_1.Air Temperature' < 4;"
