version: '3.4'

services:
    gost-db:
        image: geodan/gost-db:0.5
        volumes:
            - postgis:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        deploy:
            placement:
                constraints:
                    - node.labels.node==82
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

    gost:
        image: geodan/gost:0.5
        depends_on:
            - gost-db
        environment:
            GOST_DB_HOST: gost-db
            GOST_SERVER_EXTERNAL_URI: http://192.168.48.81:8082
            GOST_SERVER_MAX_ENTITIES: 200
        environment:
            gost_db_host: gost-db
        deploy:
            placement:
                constraints:
                    - node.labels.node==82
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

    dashboard:
        image: geodan/gost-dashboard:0.5
        ports:
          - "8082:8080"
        depends_on:
            - gost
        deploy:
            placement:
                constraints:
                    - node.labels.node==82
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

volumes:
    postgis: {}
